### ISSUE TITLE
Please update your plugins

### ISSUE THREAD

**Issue by CHJ85** [schorschii/nemo-extensions#1]
They do not seem to work no more.
I tried the Davinci plugin as well as the image compressor and none of them appear to be working. They do not show up in the menu.
EDIT! Your mistake was to add Cinnamon as the condition. Once I removed that, it worked.

**Comment by schorschii** [comment]
Thanks for your feedback. Back then when I created this I just copied a .nemo_action file from the system and did not noticed this unnecessary dependency in it. I'll remove it.

**Comment by CHJ85** [comment]
Right. Just keep the **Conditions=** part and remove the rest of the line. Otherwise it'll only work for Cinnamon users.
