### ISSUE TITLE
Shell script modification to the davinci-audio.sh to use MP4 extension and delete the original file.

### ISSUE THREAD

**Issue by robouden** [schorschii/nemo-extensions#3]
What a wonderful script for Davinci Resolve Linux users!!! Nice job.

I have been updating my file's folder by selecting all the MP4 files and converting them to ".converted.mov" files, then rename them all by rename action in Nemo.

It would be incredible if you could create a shell script that will delete the original file after conversion and then rename the converted.mov to the original .mp4 extension. That would be just one click and all conversion is done.

Regards,
Rob Oudendijk

**Comment by schorschii** [comment]
I added an option to overwrite the existing file(s) for you. Have fun and don't forget to star the repository :)

**Comment by robouden** [comment]
Whoooo!! That a fast fix/solution. Thank you.
Surely I will star your repo!!

Warm regards,
Rob Oudendijk
