### ISSUE TITLE
Compress PDF extra line

### ISSUE THREAD

**Issue by robouden** [schorschii/nemo-extensions#4]
Scorschii,

I added to the “action” line the following (borrowed from the Davinci shell of you) to have a popup what lets you know the file is still converting.

	`	| zenity --progress --text "Please wait...\n$filePath" --auto-close --pulsate --auto-kill --no-cancel"`

Warm regards,
Rob Oudendijk

**Comment by schorschii** [comment]
Thanks, I added the line into my PDF script too.

**Comment by robouden** [comment]
Thanks!!
